### ISSUE TITLE
数据字典

### ISSUE THREAD

**Issue by NoDelaySu** [stylefeng/Guns#98]
Guns开源版中如何将数据库中的数据字典加入缓存中，方便前端调用呢？

**Comment by daniel0028472** [comment]
大哥，你发错邮箱了，求求你别再往我邮箱里发东西了好吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stylefeng/Guns"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [stylefeng/Guns] 数据字典 (#98)





 
Closed #98.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
